const styles = StyleSheet.create({
  navbar: {
    paddingTop: Platform.OS === "ios" ? 40 : 20,
    paddingBottom: Platform.OS === "ios" ? 14 : 14,
    paddingHorizontal: 24,
    backgroundColor: "#0f172a", // dark navy base
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    zIndex: 10,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: "#0f172a",
    shadowOpacity: 0.9,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 20,
    elevation: 15,
  },
  logo: {
    fontSize: 28,
    fontWeight: "900",
    color: "#e0e7ff", // soft light blue
    letterSpacing: 2,
    textAlign: "center",
    flex: 1,
    textShadowColor: "rgba(224, 231, 255, 0.6)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  hamburger: {
    padding: 8,
    position: "absolute",
    right: 24,
    top: Platform.OS === "ios" ? 42 : 22,
    backgroundColor: "rgba(224, 231, 255, 0.1)",
    borderRadius: 12,
    shadowColor: "#e0e7ff",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 8,
  },
  hamburgerText: {
    fontSize: 28,
    color: "#e0e7ff",
    fontWeight: "900",
    textShadowColor: "rgba(224, 231, 255, 0.8)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  navItems: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flex: 2,
  },
  navItem: {
    marginHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    paddingHorizontal: 14,
    backgroundColor: "transparent",
    transitionDuration: "300ms",
  },
  navItemActive: {
    backgroundColor: "#6366f1", // indigo-500
    shadowColor: "#6366f1",
    shadowOpacity: 0.7,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 10,
  },
  navText: {
    color: "#cbd5e1", // light slate
    fontSize: 17,
    fontWeight: "600",
  },
  navTextActive: {
    color: "#fef3c7", // amber-100
    fontWeight: "bold",
    textShadowColor: "rgba(255, 244, 229, 0.8)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  signInButton: {
    backgroundColor: "#6366f1",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 16,
    marginLeft: 18,
    shadowColor: "#6366f1",
    shadowOpacity: 0.8,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 14,
    elevation: 12,
  },
  signInText: {
    color: "#fef3c7",
    fontWeight: "900",
    fontSize: 18,
    letterSpacing: 1,
  },
  userButton: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 18,
    backgroundColor: "#1e293b", // slate-800
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 28,
    shadowColor: "#6366f1",
    shadowOpacity: 0.6,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 10,
  },
  avatar: {
    backgroundColor: "#6366f1",
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
    shadowColor: "#6366f1",
    shadowOpacity: 0.9,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 12,
  },
  avatarText: {
    color: "#fef3c7",
    fontWeight: "900",
    fontSize: 20,
    textShadowColor: "rgba(255, 243, 199, 0.9)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
  },
  userEmail: {
    color: "#a5b4fc", // indigo-300
    fontWeight: "700",
    fontSize: 17,
  },
  centered: {
    justifyContent: "center",
    alignItems: "center",
  },
  overlay: {
    position: "absolute",
    top: Platform.OS === "ios" ? 90 : 70,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(15, 23, 42, 0.85)", // dark translucent
    zIndex: 15,
  },
  sideMenu: {
    position: "absolute",
    top: Platform.OS === "ios" ? 90 : 70,
    bottom: 0,
    left: 0,
    width: windowWidth * 0.75,
    backgroundColor: "#1e293b", // slate-800
    zIndex: 20,
    shadowColor: "#6366f1",
    shadowOpacity: 0.7,
    shadowOffset: { width: 4, height: 0 },
    shadowRadius: 20,
    elevation: 25,
    borderTopRightRadius: 24,
    borderBottomRightRadius: 24,
  },
  sideMenuHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 22,
    borderBottomColor: "#6366f1",
    borderBottomWidth: 2,
  },
  sideMenuTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#a5b4fc",
    letterSpacing: 1.5,
  },
  closeButton: {
    fontSize: 30,
    color: "#a5b4fc",
    fontWeight: "900",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: "rgba(101, 116, 255, 0.2)",
    shadowColor: "#a5b4fc",
    shadowOpacity: 0.7,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 12,
    elevation: 12,
  },
  sideMenuContent: {
    paddingTop: 14,
  },
  sideMenuItem: {
    paddingVertical: 18,
    paddingHorizontal: 28,
    borderRadius: 14,
    marginHorizontal: 14,
    marginVertical: 6,
  },
  sideMenuItemActive: {
    backgroundColor: "#6366f1",
    shadowColor: "#6366f1",
    shadowOpacity: 0.9,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 20,
    elevation: 18,
  },
  sideMenuText: {
    fontSize: 20,
    fontWeight: "600",
    color: "#cbd5e1",
  },
  sideMenuTextActive: {
    color: "#fef3c7",
    fontWeight: "bold",
    textShadowColor: "rgba(255, 244, 229, 0.9)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
  },
  userInfoSideMenu: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 28,
    paddingVertical: 24,
    borderTopColor: "#334155",
    borderTopWidth: 1,
    marginTop: 28,
  },
  avatarLarge: {
    backgroundColor: "#6366f1",
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 20,
    shadowColor: "#6366f1",
    shadowOpacity: 0.9,
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 16,
    elevation: 16,
  },
  avatarTextLarge: {
    color: "#fef3c7",
    fontWeight: "900",
    fontSize: 26,
    textShadowColor: "rgba(255, 243, 199, 0.9)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 10,
  },
  userEmailSideMenu: {
    fontSize: 20,
    fontWeight: "700",
    color: "#cbd5e1",
  },
  logoutButtonSideMenu: {
    backgroundColor: "#6366f1",
    marginHorizontal: 28,
    marginTop: 28,
    paddingVertical: 16,
    borderRadius: 20,
    alignItems: "center",
    shadowColor: "#6366f1",
    shadowOpacity: 0.9,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 20,
    elevation: 20,
  },
  logoutTextSideMenu: {
    color: "#fef3c7",
    fontWeight: "900",
    fontSize: 20,
    letterSpacing: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.85)",
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  modalContent: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderRadius: 24,
    padding: 32,
    shadowColor: "#6366f1",
    shadowOpacity: 0.5,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 30,
    elevation: 25,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    backdropFilter: "blur(20px)", // glassmorphism effect (may not work on all RN platforms)
  },
  modalTitle: {
    fontSize: 28,
    fontWeight: "900",
    marginBottom: 24,
    textAlign: "center",
    color: "#a5b4fc",
    letterSpacing: 1.5,
    textShadowColor: "rgba(165, 180, 252, 0.8)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  errorText: {
    color: "#f87171", // rose-400
    marginBottom: 20,
    textAlign: "center",
    fontWeight: "700",
    fontSize: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: "rgba(203, 213, 225, 0.4)",
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 16,
    fontSize: 18,
    marginBottom: 20,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    color: "#e0e7ff",
    shadowColor: "#6366f1",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 8,
  },
  modalButtons: {
    flexDirection: "row",
    marginTop: 16,
  },
  cancelButton: {
    backgroundColor: "rgba(203, 213, 225, 0.3)",
    paddingVertical: 16,
    borderRadius: 20,
    alignItems: "center",
  },
  cancelText: {
    color: "#cbd5e1",
    fontWeight: "700",
    fontSize: 16,
  },
});
